### ISSUE TITLE
Why not use stock header?

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#1]
Site has identical header to the stock one and yet stock is not being used. What's the reason for this?

**Comment by iliyaM** [comment]
In the header there are Facebook icons and whatsapp

בתאריך 1 בספט' 2016 15:43,‏ "Mladen Mijatov" <notifications@github.com> כתב:

**Comment by MeanEYE** [comment]
And that is not doable through main menu items why?

**Comment by iliyaM** [comment]
tall didnt tell me about it
next time
