### ISSUE TITLE
Have fallback font families defined.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#10]
In cases when there's a network error or some other reason why font file is not able to be loaded we absolutely need to make sure there's more than one font listed in `font-family` property in main style sheet.

**Comment by iliyaM** [comment]
font-family: "OpenSansHebrew", "ariel", "serif";

right?

**Comment by MeanEYE** [comment]
Arial
No quotes needed.

**Comment by iliyaM** [comment]
fixed
