### ISSUE TITLE
Increase spacing on the bottom to be symmetric to the top of the form.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#11]
![screenshot from 2016-09-07 12-22-45](https://cloud.githubusercontent.com/assets/1911594/18308721/08555540-74f6-11e6-8b8f-428eea190958.png)
As seen on screen shot spacing from the top to the bottom are not the same. Make them symmetric.

**Comment by iliyaM** [comment]
changed
