### ISSUE TITLE
Equal spacing on all section containers.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#12]
![screenshot from 2016-09-07 12-23-10](https://cloud.githubusercontent.com/assets/1911594/18308745/29a18e80-74f6-11e6-81b0-953acfc64615.png)
Issue 1 

![screenshot from 2016-09-07 12-23-21](https://cloud.githubusercontent.com/assets/1911594/18308757/35e0569a-74f6-11e6-8481-dd8fd3f3af7f.png)
Issue 2

![screenshot from 2016-09-07 12-23-39](https://cloud.githubusercontent.com/assets/1911594/18308767/3e712cda-74f6-11e6-8b1c-b70d41200651.png)
Spacing needs to be equal from the top and bottom and same value on all section containers. Suggest creating a variable `@vertical_spacing` in `main.less` and using that instead of random values. Be vary of margins on heading tags.

**Comment by iliyaM** [comment]
changed
