### ISSUE TITLE
Fix line height on phone numbers.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#13]
![screenshot from 2016-09-07 12-24-05](https://cloud.githubusercontent.com/assets/1911594/18308833/90ab2dac-74f6-11e6-851a-7cc3c5d5581a.png)
Make `line-height: 100%` on phone numbers which have border. This is so the box surrounding the phone number doesn't look off to one side.

**Comment by iliyaM** [comment]
added line-height
