### ISSUE TITLE
Button needs to have :active state as well.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#17]
![screenshot from 2016-09-07 12-35-47](https://cloud.githubusercontent.com/assets/1911594/18309033/a23d5cd8-74f7-11e6-837f-81e942d96d49.png)
When making buttons with `:hover` effect it's important to make `:active` state as well as to give the idea to the user that button is actually working. Right now it feels broken.

**Comment by iliyaM** [comment]
changed
