### ISSUE TITLE
Copyright text is poorly formatted.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#19]
Copyright should be "Improved & developed by Way2CU. All rights reserved." Lower case letters and punctuation signs are important.
![screenshot from 2016-09-07 12-38-01](https://cloud.githubusercontent.com/assets/1911594/18309103/03b51988-74f8-11e6-9d98-5e792445e218.png)

**Comment by iliyaM** [comment]
fixed
