### ISSUE TITLE
Position articles to the top.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#22]
![screenshot from 2016-09-14 10-27-12](https://cloud.githubusercontent.com/assets/1911594/18505073/d17ef916-7a65-11e6-8614-fc00d92812da.png)
Content being centered means text always starts from a different position. Without some frame to guide it it moves too much. In this case it should be aligned to the top.

**Comment by iliyaM** [comment]
fixed
