### ISSUE TITLE
Same spacing from all sides.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#23]
![screenshot from 2016-09-14 10-28-54](https://cloud.githubusercontent.com/assets/1911594/18505127/103848ba-7a66-11e6-860c-8570d83bbc6b.png)
Symmetry is a must.

**Comment by iliyaM** [comment]
fixed
![capture](https://cloud.githubusercontent.com/assets/20294485/18505316/4d3b992a-7a6f-11e6-890c-5de66b0b0839.JPG)

**Comment by MeanEYE** [comment]
Mobile version of this has borders around tabs. Don't want to see those.
