### ISSUE TITLE
Hitbox for main menu button is too small.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#25]
![screenshot from 2016-09-14 10-31-09](https://cloud.githubusercontent.com/assets/1911594/18505174/62d00f72-7a66-11e6-8a7f-1329a2460e1f.png)
It's obvious you are copypasting bullshit from Tal since he makes the same mistake. This is an issue because your actual hitbox is tiny and it will be difficult to hit it with fingers. You need to make `<a>` have the full proper size so it's easy to hit.

**Comment by iliyaM** [comment]
im not copy pasting i build it myself 
i did stole the idea though 
is that good?
![capture](https://cloud.githubusercontent.com/assets/20294485/18505585/9ab87be0-7a70-11e6-83b1-4f3ce4bbc97d.JPG)

**Comment by MeanEYE** [comment]
You are copy pasting because issue is the same. From all the things you could take you took the worst. And not it's not okay. Add `outline: 1px solid white` to `a.menu` and you'll see where the problem is. That's what you have to click on for menu to show. `:before` and `:after` don't accept events.

**Comment by iliyaM** [comment]
fixed
