### ISSUE TITLE
Fix tab control and its content.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#29]
![screenshot-2016-09-14_517x194](https://cloud.githubusercontent.com/assets/1911594/18505664/9452dadc-7a68-11e6-8aa2-91bf3640c162.png)
![screenshot-2016-09-14_458x202](https://cloud.githubusercontent.com/assets/1911594/18505669/9d8b5188-7a68-11e6-9b82-86d49ce72eaf.png)

**Comment by iliyaM** [comment]
fixed
