### ISSUE TITLE
Fix sizing issues in landscape mode.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Primavera-Constipation-Site#31]
My claims not to use fixed `height: xxx` are for a reason. And this case is the the prime example. You are using `height` attribute for mobile title but determining logo size based on display width.
![screenshot-2016-09-14_795x278](https://cloud.githubusercontent.com/assets/1911594/18505895/ad66a746-7a69-11e6-9c64-a89815f0b05d.png)

**Comment by MeanEYE** [comment]
![screenshot-2016-09-14_806x407](https://cloud.githubusercontent.com/assets/1911594/18505910/c568c266-7a69-11e6-8853-10960a121d2e.png)

**Comment by iliyaM** [comment]
fixed
